
" This file contains the settings specific to NeoVim.

if has('nvim')

    " nvim specific. Integrates the vim buffers with the system clipboard.
    set clipboard+=unnamedplus

    " Update the terminal mode so the Esc char changes to normal mode.
    tnoremap <Esc> <C-\><C-n>

    " Key mappings for making Vim split navigation easier.
    tnoremap <C-h> <C-\><C-n>:wincmd h<CR>
    tnoremap <C-j> <C-\><C-n>:wincmd j<CR>
    tnoremap <C-k> <C-\><C-n>:wincmd k<CR>
    tnoremap <C-l> <C-\><C-n>:wincmd l<CR>

    " Upon entering a terminal window, go to insert mode so you can start
    " doing terminal things immediately.
    autocmd BufWinEnter,WinEnter term://* startinsert
endif

