
" This file contains the settings specific to NeoVim.

if has('nvim')

    " nvim specific. Integrates the vim buffers with the system clipboard.
    set clipboard+=unnamedplus

    " Update the terminal mode so the Esc char changes to normal mode.
    tnoremap <Esc> <C-\><C-n>

    " These are the characters sent by the equivalient Alt-? combinations on
    " the default keyboard mapping for a Mac.
    tnoremap è <C-\><C-n>:wincmd h<CR>
    tnoremap ê <C-\><C-n>:wincmd j<CR>
    tnoremap ë <C-\><C-n>:wincmd k<CR>
    tnoremap ì <C-\><C-n>:wincmd l<CR>

    " Upon entering a terminal window, go to insert mode so you can start
    " doing terminal things immediately.
    autocmd BufWinEnter,WinEnter term://* startinsert

    if filereadable($HOME . "/.pyenv/versions/neovim-2.7/bin/python")
        let g:python_host_prog=$HOME . "/.pyenv/versions/neovim-2.7/bin/python"
    endif
    if filereadable($HOME . "/.pyenv/versions/neovim-3.4/bin/python")
        let g:python3_host_prog=$HOME . "/.pyenv/versions/neovim-3.4/bin/python"
    endif

    " While substitutions are in progress, this highlight matches as you type,
    " and then show what the replacement will look like while you enter the
    " replacement text.
    set inccommand=split

    " Configuration of the NeoTerm plugin.
    " Position was deprecated in favor of default_mod.
    "let g:neoterm_position = 'horizontal'
    let g:neoterm_default_mod = 'rightbelow'
    let g:neoterm_automap_keys = ',tt'

    nnoremap <silent> ,sf :TREPLSendFile<cr>
    nnoremap <silent> ,sl :TREPLSendLine<cr>
    vnoremap <silent> ,ss :TREPLSendSelection<cr>

    " run set test lib
    nnoremap <silent> ,ra :call neoterm#test#run('all')<cr>
    nnoremap <silent> ,rf :call neoterm#test#run('file')<cr>
    nnoremap <silent> ,rc :call neoterm#test#run('current')<cr>
    nnoremap <silent> ,rr :call neoterm#test#rerun()<cr>

    " Useful maps
    " hide/close terminal
    nnoremap <silent> ,th :call neoterm#close()<cr>
    " clear terminal
    nnoremap <silent> ,tl :call neoterm#clear()<cr>
    " kills the current job (send a <c-c>)
    nnoremap <silent> ,tc :call neoterm#kill()<cr>

    source ~/home-dir/vim/nvimrc-golang
endif
