
" This file contains the settings specific to NeoVim.

if has('nvim')

    " nvim specific. Integrates the vim buffers with the system clipboard.
    set clipboard+=unnamedplus

    " Update the terminal mode so the Esc char changes to normal mode.
    tnoremap <Esc> <C-\><C-n>

    " These are the characters sent by the equivalient Alt-? combinations on
    " the default keyboard mapping for a Mac.
    tnoremap è <C-\><C-n>:wincmd h<CR>
    tnoremap ê <C-\><C-n>:wincmd j<CR>
    tnoremap ë <C-\><C-n>:wincmd k<CR>
    tnoremap ì <C-\><C-n>:wincmd l<CR>

    " Upon entering a terminal window, go to insert mode so you can start
    " doing terminal things immediately.
    autocmd BufWinEnter,WinEnter term://* startinsert

    if filereadable($HOME . "/.pyenv/versions/neovim2/bin/python")
        let g:python_host_prog=$HOME . "/.pyenv/versions/neovim2/bin/python"
    endif
    if filereadable($HOME . "/.pyenv/versions/3.7.0/bin/python")
        let g:python3_host_prog=$HOME . "/.pyenv/versions/neovim3/bin/python"
    endif

    " While substitutions are in progress, this highlight matches as you type,
    " and then show what the replacement will look like while you enter the
    " replacement text.
    set inccommand=split
endif
